/** @type {import('tailwindcss').Config} */
// Color tokens copied from stitch/code.html — "The Technical Atelier"
// Material Design 3 palette. Single source of truth for the design system.
export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#4d44e3',
        'primary-dim': '#4034d7',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#d2d0ff',
        'primary-container': '#e2dfff',
        'on-primary': '#faf6ff',
        'on-primary-fixed': '#2a13c5',
        'on-primary-container': '#3f33d6',
        secondary: '#605e62',
        'secondary-dim': '#545256',
        'secondary-container': '#e5e1e6',
        'on-secondary': '#fcf8fc',
        'on-secondary-container': '#525155',
        tertiary: '#575e78',
        'tertiary-dim': '#4b526c',
        'tertiary-container': '#d2d9f8',
        'tertiary-fixed': '#d2d9f8',
        'on-tertiary': '#faf8ff',
        'on-tertiary-container': '#444c65',
        error: '#9e3f4e',
        'error-container': '#ff8b9a',
        'on-error': '#fff7f7',
        'on-error-container': '#782232',
        background: '#f8f9fa',
        'on-background': '#2b3437',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d1dce0',
        'surface-tint': '#4d44e3',
        'surface-variant': '#dbe4e7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#eaeff1',
        'surface-container-high': '#e2e9ec',
        'surface-container-highest': '#dbe4e7',
        'on-surface': '#2b3437',
        'on-surface-variant': '#586064',
        outline: '#737c7f',
        'outline-variant': '#abb3b7',
        'inverse-surface': '#0c0f10',
        'inverse-on-surface': '#9b9d9e',
        'inverse-primary': '#8582ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
};
